### ISSUE TITLE
S3 storage not listing s3 size/objects/empty buckets 

### ISSUE THREAD

**Issue by akshayatplivo** [mlabouardy/komiser#107]
Hi there, 

S3 storage not listing s3 size/objects/empty buckets still doesnt seem to work. After reviewing the previous issues related to IAM permissions i have provided full admin access and see it still doesn't work. 

What am i doing wrong?

Thanks.

**Comment by pocketcalculator** [comment]
The source code is checking for an actual permission (like "s3:ListAllMyBuckets") as opposed to "s3:*" which should still work.  If it doesn't see the former, it throws a 500.  The best workaround for now is to create create an IAM role with the policy referenced in the installation instructions: https://komiser.s3.amazonaws.com/policy.json

**Comment by akshayatplivo** [comment]
@pocketcalculator  Done all of that and still get no result for those 3 fields. Tried on various browsers as well and see the same result. 

There must be something wrong here. Also just to be on the same page, i am running on 2.3.0.

Thanks.

**Comment by akshayatplivo** [comment]
@mlabouardy Any help here? Have tried and tested every way, with no luck. 

Thanks

**Comment by akshayatplivo** [comment]
@mlabouardy  A quick update. I see all the details listing fine for a fewer number of buckets.. Say <150~200..

However for my production account we have 456 buckets and the remaining shows 0 data. 

Maybe a bug/issue? 

Will be great if you could look into this.

**Comment by CyrilAll** [comment]
it might be due to the pagination when the listBuckets request is called - it's not yet supported

**Comment by mlabouardy** [comment]
Fixed, here [v2.5.0](https://github.com/mlabouardy/komiser/releases/tag/2.5.0)
