### ISSUE TITLE
Documentation for Azure support

### ISSUE THREAD

**Issue by zimgodo** [mlabouardy/komiser#109]
As per #81, although the question was closed and being noted that Azure will be added in komiser, there is still yet any documentation available for it.

Any chance to having this soon?

Thank you.

**Comment by zimgodo** [comment]
Looking at the codes, unless I'm looking at the wrong places, it didn't have any support for azure under `services` either.

**Comment by Sup3rlativ3** [comment]
I'm also interested in this. I've been following for a while as Azure support was said to be coming but I'm yet to see it.

**Comment by Sup3rlativ3** [comment]
@mlabouardy Can you please shed some light on Azure support?

**Comment by andrei-dascalu** [comment]
Azure is listed as a supported Cloud provider in the docs, but no documentation on how to use it. I also can't find anything in the code pointing to Azure.

**Comment by CyrilAll** [comment]
We will be add the documentation for azure in the coming weeks. Just for your information, Compute & Storage is supported right now, not other services.

By the way, we are looking for maintainers so if you want are interested to help develop the missing features for azure, feel free to join us on slack at:  https://community.komiser.io/
