### ISSUE TITLE
Using roles to access to services rather than an IAM user

### ISSUE THREAD

**Issue by mderoquefeuil** [mlabouardy/komiser#111]
Hello,

I would like to experiment komiser for my company, we work with multiple accounts and a billing account. 
We have a strict security policy so we do not log into AWS by using IAM users but with roles and AFDS. 

Is there any plan to allow this kind of authentication in a short future ? I wouldn't mind contributing to make this feature available, if that's in my capabilities :-)

Martin

**Comment by sebastian-rojas** [comment]
This would be extremely useful, most organizations nowadays are relying on assumed roles and moving away from "hard coded keys". Tools such as OKTA (aws-okta) and so on... makes it easier to run these tools.

**Comment by spaghettifunk** [comment]
We have deployed Komiser in Kubernetes on EKS and we do use IAM Role for accessing the resources. To do so, we have `kube2iam` that helps the pods to assume the role. How do you plan deploying the application?

**Comment by mderoquefeuil** [comment]
Hello, 

Ideally I would deploy an autonomous application that access each and every account to inspect cost and aggregate datas in a single panel.

Not sure this is what you did.

Sorry for the delay, totally missed I had notifications.

**Comment by CyrilAll** [comment]
It's part of the roadmap ! If you still wanna help us develop this feature, feel free to join us on slack at https://community.komiser.io/ !
