### ISSUE TITLE
Cloud Komiser Signup CORS Error

### ISSUE THREAD

**Issue by huseyinozkilic** [mlabouardy/komiser#113]
I was trying a signup for your cloud portal but given me this error from your panel.

Access to XMLHttpRequest at 'https://gkihg5bewc.execute-api.eu-central-1.amazonaws.com/production/v1/signup' from origin 'https://cloud.komiser.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Form address: https://cloud.komiser.io/signup

Post Package: {
  "firstName": "Huseyin",
  "lastName": "OZKILIC",
  "company": "None",
  "email": "huseyin.ozkilic@windowslive.com",
  "password": "123456"
}

**Comment by CyrilAll** [comment]
already fixed ! Thanks for reporting :)
