### ISSUE TITLE
"Account with  doesnt not exist"

### ISSUE THREAD

**Issue by huseyinozkilic** [mlabouardy/komiser#114]
Im login with github account but still so many errors in here.

Url: https://cloud.komiser.io/dashboard

https://gkihg5bewc.execute-api.eu-central-1.amazonaws.com/production/v1/aws/iam/users
Response: {"error":"Account with  doesnt not exist"}

https://i.ibb.co/gr6kxR7/cloud-komiser-dashboard.jpg

Other one;
https://i.ibb.co/3FGdkvg/cloud-komiser-dashboard-console.jpg

**Comment by huseyinozkilic** [comment]
is also funny "doesnt not" :)

**Comment by bbenson29** [comment]
Having the same issue, added account but not registering. Using the same keys works on the local install.

**Comment by CyrilAll** [comment]
The typo is fixed, can you share with us your permissions that you have used so we can investigate the issue? Thanks !

**Comment by huseyinozkilic** [comment]
Hi, I can loged in with github account.
when I was tryin to signup responded me to empty resource, there is no given errors :)

with another mail adress.
![image](https://user-images.githubusercontent.com/529384/106219151-dd1ef580-61e9-11eb-918d-0ad21f4e1867.png)

and then :)

![image](https://user-images.githubusercontent.com/529384/106219662-eb214600-61ea-11eb-98f9-fd33f4f61d13.png)

thanks :)

**Comment by mlabouardy** [comment]
Fixed
