### ISSUE TITLE
Custom base URL

### ISSUE THREAD

**Issue by mboret** [mlabouardy/komiser#115]
Hi,

It seems not possible to define a custom base URL(example: https://example.com/komiser/). 
Could be nice to be able to set it as a command-line parameter("--base-url").
Don't really know, how difficult is to implement this. I suppose that we need to update the base URL in the main.go but also change it in Angular(no idea how to pass it the base url value).

Matthieu

**Comment by spaghettifunk** [comment]
I'm not entirely sure what do you mean with it. We have deployed Komiser in Kubernetes on a specific URL and mounted on indeed the `/komiser` path. The result for us looks like `https://my-company.com/komiser` and it works fine.

Can I ask you how you deploy Komiser?

**Comment by luiscosio** [comment]
@spaghettifunk Any walkthrough to deploy in Kubernetes? Are you using Amazon EKS?

**Comment by spaghettifunk** [comment]
I will make the helm chart public today and tag you so you can use it 😄

**Comment by luiscosio** [comment]
@spaghettifunk Thank you!

**Comment by spaghettifunk** [comment]
@luiscosio here is the helm chart (https://github.com/spaghettifunk/komiser-helm). If you have issues, please open an issue on that repository. PRs are always welcome 😄 

FYI, that is a bare minimum Komiser installation that takes some assumptions. For example, it assumes that you use AWS IAM Role for authentication instead of the ENV Variables.

**Comment by CyrilAll** [comment]
@spaghettifunk Great job and thanks for the helm chart !
@mboret it has been added to the roadmap, we'll keep you informed as soon as it's ready ! Thanks for the inputs

**Comment by mlabouardy** [comment]
Thanks a lot @spaghettifunk, we've created a helm chart based on your contribution 🙏🏻 
https://github.com/komiserio/helm
