### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by spaghettifunk** [mlabouardy/komiser#118]
Hi! I made an initial work of an [Helm Chart](https://github.com/spaghettifunk/komiser-helm) for this awesome project 🚀. I'd like some help to extend it for supporting other cloud providers because currently it supports only AWS 😄 
Once it's ready we can submit it to the official helm chart incubator.

What do you think?

**Comment by CyrilAll** [comment]
@spaghettifunk Hey ! Thanks again for the helm chart. Are you still interested in developing this feature? If yes, feel free to join us on slack at this address: https://community.komiser.io/ :)

**Comment by spaghettifunk** [comment]
I don't use it anymore unfortunately because I deployed for my previous company. Although, I can donate the repository to you if you like 😄
