### ISSUE TITLE
Brew install fails

### ISSUE THREAD

**Issue by Chewbee** [mlabouardy/komiser#119]
Brew install fails 
Download is ok 
`$ brew install komiser
==> Installing komiser from komiserio/komiser
==> Downloading https://cli.komiser.io/2.4.0/osx/komiser
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 4e4951a12658de0c8bf15806765ae2c6b5b734e45efbef54d2504d1dd1709b71
  Actual: 8958fdec8ae105ecef94fd7d253407f7ecfbdf678dd35ef8c037fd43c623fb86
 Archive: /Users/gportefait/Library/Caches/Homebrew/downloads/f32e48996ec2f93bc8274403fba68d229a189861ba05256289577a936b08f353--komiser
To retry an incomplete download, remove the file above.`

Triied 3 times

**Comment by mkj28** [comment]
<putting tinfoil hat on> this would definitely be a worthy code to compromise to get all of these AWS credentials :)

**Comment by rafaljanicki** [comment]
Note as it's related: https://github.com/mlabouardy/komiser/issues/99

I'm afraid that this project lost focus though

**Comment by CyrilAll** [comment]
Hello @Chewbee. Thanks for the input. Could you check the latest version at this url https://github.com/komiserio/homebrew-komiser if you still have the issue? Thanks again
