### ISSUE TITLE
IBM Cloud support

### ISSUE THREAD

**Issue by jjasghar** [mlabouardy/komiser#120]
Hi!

I'd like to ask for [IBM Cloud](https://cloud.ibm.com) support for your application. I work for IBM and I'm extremely impressed with the work you've done and would love to help/guide whatever to get IBM Cloud support here also.

Never hesitate to reach out at awesome@ibm.com (yes really) directly if i can ever help.

**Comment by jjasghar** [comment]
https://cloud.ibm.com/apidocs?category=platform_services i think is what you need.

**Comment by CyrilAll** [comment]
Hello @jjasghar. Sorry for the (very) late reply. The project has been on hold but it's back on track ! We'll send you an email in the coming hours :) ! Meanwhile, if you want, you can join us on slack at this address: https://community.komiser.io/
