### ISSUE TITLE
Windows instruction not valid

### ISSUE THREAD

**Issue by JamesWoolfenden** [mlabouardy/komiser#121]
The instructions in your readme should be wget https://cli.komiser.io/2.4.0/windows/komiser -OutFile Komiser.exe. You need to state the outfile and that's its an exe.
Then it runs fine!

**Comment by CyrilAll** [comment]
Thanks for the input ! Would you mind opening a PR with this fix? Many thanks in advance !

**Comment by mlabouardy** [comment]
Thanks for the tip @JamesWoolfenden, I've updated the [README](https://github.com/mlabouardy/komiser/commit/5967a96444df670ba1819ab6a75b1f169c950cdf)
