### ISSUE TITLE
Get requests giving Internal Server error

### ISSUE THREAD

**Issue by swarnimshukla** [mlabouardy/komiser#123]
I was trying to run the project locally but only some of the get requests are getting through. Most of the get request are giving status code error 500.
![Screenshot from 2019-10-30 14-52-22](https://user-images.githubusercontent.com/29918260/67845292-4286c100-fb25-11e9-88ca-0753c825ed7e.png)

**Comment by swarnimshukla** [comment]
@mlabouardy, can you help me out regarding this???

**Comment by CyrilAll** [comment]
Hello @swarnimshukla ! Would you mind checking your permission policies and ensure it's the same as this file: https://github.com/mlabouardy/komiser/blob/master/policy.json. It should solve your issues, tell us if it's not the case. Thanks
