### ISSUE TITLE
installation error via brew

### ISSUE THREAD

**Issue by developer-guy** [mlabouardy/komiser#124]
when i typed *brew install komiser* to my terminal , i got a followed error below : 

Updating Homebrew...
==> Installing komiser from komiserio/komiser
==> Downloading https://cli.komiser.io/2.4.0/osx/komiser
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 4e4951a12658de0c8bf15806765ae2c6b5b734e45efbef54d2504d1dd1709b71
  Actual: 8958fdec8ae105ecef94fd7d253407f7ecfbdf678dd35ef8c037fd43c623fb86
 Archive: /Users/xyz/Library/Caches/Homebrew/downloads/f32e48996ec2f93bc8274403fba68d229a189861ba05256289577a936b08f353--komiser
To retry an incomplete download, remove the file above.

**Comment by gari1995** [comment]
exactly same problem same problem for me..... 
Anyone knows how to fix it? I would really appreciate it

**Comment by bashou** [comment]
For those who can't install through brew, there is a workarround.
Before (re)installing, use `brew edit komiser`, set expected hash, save and `brew install komiser`.

It's not really advised (prefer docker container instead), but if you really need to use brew, that's "a way".
