### ISSUE TITLE
Network section --> CloudFront Incoming Requests: Distribution list truncated

### ISSUE THREAD

**Issue by CaseyLabs** [mlabouardy/komiser#125]
Hi there,

First off, just wanted to say that my first test of Komiser has been a pleasant surprise... you've developed a really clear/great UI!

Minor issue that I've encountered:

- Log into Komiser
- Left-column: click on Network
- Scroll down to "Cloudfront Incoming Requests"
- Mouse-over to a section on the Cloudfront graph. If there are more than 5 Cloudfront distributions, the list gets truncated:

![screenshot](https://user-images.githubusercontent.com/4674433/71855835-00cf4500-3097-11ea-9f8f-3fd9dbf1094d.png)

Is there a way to zoom-in/dive in for a complete list of Cloudfront distributions, and number of requests they've received?

Thanks!

**Comment by CyrilAll** [comment]
Hello !
Thanks for the inputs, it's in the roadmap and we'll work on that soon !
