### ISSUE TITLE
Missing Permissions on docker ECS

### ISSUE THREAD

**Issue by ThomasVdBerge** [mlabouardy/komiser#126]
I have komiser running on an ECS cluster and have provided the following credentials https://github.com/mlabouardy/komiser/blob/master/policy.json on a task role.

On top of that, I also specified the AWS_DEFAULT_REGION env var (eu-west-1).

Everything seems to be working, except the following permission errors:
- iam:GetUser is missing
-  support:DescribeCases is missing
- cloudwatch:GetMetricStatistics is missing

They are clearly there in the list, so no idea why I am seeing this error

**Comment by ThomasVdBerge** [comment]
- cloudwatch:GetMetricStatistics got resolved when I specified the default region to be us-east-1. Which means that AWS_DEFAULT_REGION always needs to be set to  us-east-1.

- support:DescribeCases is probably broken because of the following error
> An error occurred (SubscriptionRequiredException) when calling the DescribeCases operation: AWS Premium Support Subscription is required to use this service.

- iam:GetUser is still broken and does work when I execute it via cli manually

**Comment by CyrilAll** [comment]
Thanks @ThomasVdBerge for your inputs, we'll look into it soon
