### ISSUE TITLE
Multiple DigitalOcean Accounts

### ISSUE THREAD

**Issue by voidspacexyz** [mlabouardy/komiser#128]
With DigitalOcean Teams coming out, the usage of multiple accounts is becoming prevalent. Currently the project is limited to only one digitalaccount. Would like to see if we could also support multiple DO accounts just like how we support AWS.

**Comment by CyrilAll** [comment]
The enterprise version supports multiple DO accounts. We are working on it to make it available into the community edition too ! We'll keep you updated.
