### ISSUE TITLE
Inventory across all AWS regions

### ISSUE THREAD

**Issue by suren2306** [mlabouardy/komiser#129]
I have multiple EC2 instances running across different regions. If I set the default region in aws config file only the resources from that particular region are listed in the dashboard. I want omiser to list all the resources from across different regions. Is there any workaround for this?

**Comment by yashshanker** [comment]
Hey @mlabouardy , could you possibly guide me on this, I would like to contribute to this feature.
Of course, only if you think you'd want to offer this in the open source version.

**Comment by CyrilAll** [comment]
@yashshanker Hey ! We are looking for maintainers, join us on https://community.komiser.io/ !
@suren2306 Can you check if your iam policy does not prevent komiser to check resources outside of a given region? It could be the cause of your issue, tell us if it's not the case !

**Comment by suren2306** [comment]
Even tried with full access, still restricted to the default region configured in the  AWS config file

**Comment by mlabouardy** [comment]
We've done a fix @suren2306, it should list all instances across AWS regions
