### ISSUE TITLE
Missing S3 Glacier

### ISSUE THREAD

**Issue by rgarrigue** [mlabouardy/komiser#131]
Hi

I can't see S3 Glacier in the UI. Can you add it ?

Best regards,

**Comment by CyrilAll** [comment]
@rgarrigue Hello ! Thanks for the input, we've added your request to the roadmap ! We'll keep you updated.

**Comment by mlabouardy** [comment]
@rgarrigue we added the Glacier support recently https://github.com/mlabouardy/komiser/commit/b19f31644d734d885c49d6124f2c822fd1dfac3a
