### ISSUE TITLE
Full usage instructions for Docker based hosting solution [documentation]

### ISSUE THREAD

**Issue by yashshanker** [mlabouardy/komiser#133]
In my use, I've found a proper documentation missing for Docker based usage, like Using multiple aws accounts, etc.

Would love for someone to do that documentation, or if @mlabouardy could guide me on this, I can document the same. Would love to.

**Comment by lgallard** [comment]
I think you can copy a ~/.aws/credentials, but I would rather be able to pass variables to multi account and to multi-clouds

I agree that is a lack of information for using the docker solution!

**Comment by yashshanker** [comment]
I’ve tried mounting ~/.aws/credentials file in the docker image, and it doesn’t work.

Yes proper directions are needed for docker usage.

**Comment by CyrilAll** [comment]
@yashshanker you can still join us on slack https://community.komiser.io/ to discuss how you can contribute to this project :) !
