### ISSUE TITLE
Error Downloading Komiser for Mac: SHA256 mismatch

### ISSUE THREAD

**Issue by andrewsavino1** [mlabouardy/komiser#134]
Steps taken, following the readme:

1. `wget https://cli.komiser.io/2.4.0/osx/komiser` (this actually failed for me, I re-ran it with the `--no-check-certificate` flag.)

2. `brew tap komiserio/komiser`

3. `brew install komiser`

Result:

```
Updating Homebrew...
==> Installing komiser from komiserio/komiser
==> Downloading https://cli.komiser.io/2.4.0/osx/komiser
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 4e4951a12658de0c8bf15806765ae2c6b5b734e45efbef54d2504d1dd1709b71
  Actual: d55a3f539d659a4d36ad5fbf68c979709f1223ffd6bd870caff53975ee5c2eb6
 Archive: {home}/Library/Caches/Homebrew/downloads/f32e48996ec2f93bc8274403fba68d229a189861ba05256289577a936b08f353--komiser
To retry an incomplete download, remove the file above.
```

**Comment by rahulpatilgit** [comment]
Follow the below steps to resolve the issue - 
1. Edit the below file and change the sha value and rerun the **brew install komiser**
**/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/komiserio/homebrew-komiser/Formula/komiser.rb**
![image](https://user-images.githubusercontent.com/36784101/91659646-c5362f00-eaee-11ea-9dbc-8ef6a87503eb.png)

**Comment by mikkiwright** [comment]
I was also getting this error on Mac. The solution mentioned above by @rahulpatilgit works but I struggled to find the file on mac. For anyone else struggling it's found here:
**/usr/local/Homebrew/Library/Taps/komiserio/homebrew-komiser/Formula/komiser.rb**

**Comment by CyrilAll** [comment]
@rahulpatilgit @mikkiwright Hello, thanks for your solution ! Would you mind creating a PR with your solution to update this file: https://github.com/komiserio/homebrew-komiser/blob/master/Formula/komiser.rb?
Thanks a lot in advance :)

**Comment by mlabouardy** [comment]
@andrewsavino1 @mikkiwright thanks for reporting the issue
I've done the fix [here](https://github.com/komiserio/homebrew-komiser/commit/029ae1ee83a3d6a6b01458f504f2d811fd0877ab), also the latest release support now Azure :)

**Comment by Ga13Ou** [comment]
@mlabouardy The same problem happens with the version 3.0.3 apparently.

**Comment by mlabouardy** [comment]
> @mlabouardy The same problem happens with the version 3.0.3 apparently.

thanks @Ga13Ou for reporting the issue
@jakepage91 can you check the sha256 of the brew package

**Comment by Yawmiej** [comment]
Experienced this too on 3.0.3

**Comment by jakepage91** [comment]
Thanks for pointing this out @Yawmiej, fixed! 

Try running:
```
brew update
brew reinstall komiser
```

**Comment by Yawmiej** [comment]
@jakepage91, the problem still seems to exist.

Although I already downloaded using `wget`

**Comment by jakepage91** [comment]
True @Yawmiej , the SHA checksum associated to **AMD** package was out of date. Now fixed so both **AMD and ARM** versions are updated and should successfully download using `brew`

```
brew update
brew reinstall komiser
```
