### ISSUE TITLE
EBS volumes show wrong unit

### ISSUE THREAD

**Issue by manjumaikan** [mlabouardy/komiser#136]
![image](https://user-images.githubusercontent.com/35387096/93696714-b58f9080-fb58-11ea-95e5-757f1e9d13c5.png)

The actual size is 50GB.

**Comment by CyrilAll** [comment]
Hello @manjumaikan . Thanks for your input, we'll investigate this issue and will keep you updated

**Comment by mlabouardy** [comment]
@manjumaikan we fixed the size's unit https://github.com/mlabouardy/komiser/commit/71601b35cdcc2ca0265898359bcfd3fe3f05c0e1
