### ISSUE TITLE
map is not displayed. Also 'support:DescribeCases is missing' is displayed even after using the attached policy.

### ISSUE THREAD

**Issue by manjumaikan** [mlabouardy/komiser#137]
![image](https://user-images.githubusercontent.com/35387096/93698480-41092180-fb59-11ea-832a-a26b4e910346.png)

**Comment by CyrilAll** [comment]
Hello again !
the issue support:Describe... is the same as #130 
As for the map, we'll try to reproduce on our side the issue to solve it !

**Comment by mlabouardy** [comment]
Fixed @manjumaikan with latest version [v2.5.0 ](https://github.com/mlabouardy/komiser/releases/tag/2.5.0) (we released the Azure support as well)
