### ISSUE TITLE
Question:  Is the project still under active development?

### ISSUE THREAD

**Issue by graftan** [mlabouardy/komiser#138]
Hello @mlabouardy - what's the current state of the project?

It looks like a very cool tool. However, I've noticed there hasn't been any commits in a long time.  

Is it still under active development?
Who is the current maintainer of this project?
Is the current maintainer accepting of pull requests or contributions?

Thanks for any help you can provide.

**Comment by CyrilAll** [comment]
@graftan Hello ! Hope you are well.
The project was on hold but we have put it back to life AND we are looking for maintainers. If you want to contribute, join us on slack to discuss at : https://community.komiser.io/
