### ISSUE TITLE
EC2 Rightsizing & RDS RI Recommendations

### ISSUE THREAD

**Issue by alb777** [mlabouardy/komiser#139]
Add the feature to show in table mode the Rightsizing & RDS RI Recommendation

**Comment by CyrilAll** [comment]
Hello Alberto ! thanks for your insight but we are not sure to have fully understood your feature request. Would you mind explain it a little bit more? Thanks !

**Comment by albertogalinari** [comment]
Even using trial premium features licensing RightSizing, RI and Cost Optimization options aren`t available.
