### ISSUE TITLE
Support for GCP organizations strukture - many folders, many projects

### ISSUE THREAD

**Issue by pmalczuk** [mlabouardy/komiser#149]
For now I can configure one project. Any solution for multi project organizations is planned?
https://cloud.google.com/resource-manager/docs/cloud-platform-resource-hierarchy#cloud_platform_resource_hierarchy_and_iam_policy_hierarchy

**Comment by CyrilAll** [comment]
Hello ! Thanks for your feedback.
Right now there is no solution to do that in the community edition. However, if you use the website version, you'll be able to do that !
