### ISSUE TITLE
web preview site: not authorized error when creating new aws account

### ISSUE THREAD

**Issue by JeffMangan** [mlabouardy/komiser#152]
Something went wrong ! couldn't add a new account.
{"message":"Unauthorized"}

Request URL: https://gkihg5bewc.execute-api.eu-central-1.amazonaws.com/production/v1/accounts
Request Method: POST
Status Code: 401 
Remote Address: 18.194.248.175:443
Referrer Policy: strict-origin-when-cross-origin
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, HEAD, OPTIONS
Access-Control-Allow-Origin: https://cloud.komiser.io
content-length: 26
content-type: application/json
date: Thu, 18 Mar 2021 15:21:41 GMT
x-amz-apigw-id: cY5w6FIeliAFa_A=
x-amzn-errortype: UnauthorizedException
x-amzn-requestid: d0053066-b564-4012-91e8-57588774d201
:authority: gkihg5bewc.execute-api.eu-central-1.amazonaws.com
:method: POST
:path: /production/v1/accounts
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: eyJraWQiOiJ1cXIxN3JnV2ZzQjFaZUlJeW1Jd01SQ1BQUnRCVWVWdFdYNVJMWXd6amp3PSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiTkc5UmlVcl94TExRY2c0SGFBVmFXdyIsInN1YiI6IjhiMjE2MzE0LTFiNmMtNGZlZC1hOGZkLThhZjIyOTUzOTkwYyIsImNvZ25pdG86Z3JvdXBzIjpbImV1LWNlbnRyYWwtMV9Vd3B1VjFvVmpfR2l0SHViIl0sImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcm9maWxlIjoiaHR0cHM6XC9cL2dpdGh1Yi5jb21cL0pNLVRXIiwiY3VzdG9tOmxhc3ROYW1lIjoiTWFuZ2FuIiwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tXC9ldS1jZW50cmFsLTFfVXdwdVYxb1ZqIiwiY29nbml0bzp1c2VybmFtZSI6IkdpdEh1Yl82MjA4MTMyMSIsInBpY3R1cmUiOiJodHRwczpcL1wvYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb21cL3VcLzYyMDgxMzIxP3Y9NCIsImN1c3RvbTpjb21wYW55IjoiSk1hbmdhbiIsImF1ZCI6IjVlcmRrZjMwOXRhOGU5MnFjdjZybzBxZGMzIiwiY3VzdG9tOnBob25lIjoiNDgwMjE2Mzk3MiIsImlkZW50aXRpZXMiOlt7InVzZXJJZCI6IjYyMDgxMzIxIiwicHJvdmlkZXJOYW1lIjoiR2l0SHViIiwicHJvdmlkZXJUeXBlIjoiT0lEQyIsImlzc3VlciI6bnVsbCwicHJpbWFyeSI6InRydWUiLCJkYXRlQ3JlYXRlZCI6IjE2MTQwMDgwNjg3ODMifV0sImN1c3RvbTpmaXJzdE5hbWUiOiJKZWZmIiwidXBkYXRlZF9hdCI6MTYxNDAxMjI3NywidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2MTQwMDgwNzMsIm5hbWUiOiJKZWZmIE1hbmdhbiIsImV4cCI6MTYxNjA4MzM3NCwiaWF0IjoxNjE2MDc5Nzc1LCJlbWFpbCI6ImplZmYubWFuZ2FuQHRob3VnaHR3b3Jrcy5jb20ifQ.0p5ahcI7grLk1HxwggzKdtqOq8BAshzPV4boWzD2kXd86yYTMOjqJnkw4tAID3iFgylKQGifErlHp8aM-b9tn4WtOtLxXzO-Gaah24YJa9JYQ-43wLCNJ7eCoohLV5dOr0shs8_AIg6zs8XkQYRWXcKvWFcyRnmIpI3myhqt251W9DQFiCa3h2CTgt5Sfx79V482C8ZDSqVV4IdPEHUTTuezwGtD25p6igM_1P4MjaV4PF8lZzDR0XFCA99XxiXG4VTS18swNKnjoSrAXZQZrXA9r9_OfhBTL-GFlfRJNQxotUyC3MXOrpu-HSEvRe7DdkhdRhDbuy_Y5blHP9CAOQ
content-length: 159
content-type: application/json
dnt: 1
origin: https://cloud.komiser.io
referer: https://cloud.komiser.io/
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
{provider: "aws", awsRegion: "cn-northwest-1", awsAccessKey: "adfs", awsSecretKey: "adsfasf",…}
awsAccessKey: "adfs"
awsRegion: "cn-northwest-1"
awsSecretKey: "adsfasf"
id: "8b216314-1b6c-4fed-a8fd-dasfafdas"
provider: "aws"

**Comment by mlabouardy** [comment]
We've done a fix, also we just released Azure support as well :)
