### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by jtbonhomme** [mlabouardy/komiser#154]
Hello Mohamed,
I tried to install komiser today (homebrew), and it failed due to a signature mismatch.
![image](https://user-images.githubusercontent.com/2371465/115270567-b911e700-a13c-11eb-8b21-b4403d196a7a.png)
Cheers !
JT

**Comment by sourabh-kalal** [comment]
@jtbonhomme You can install it with "wget https://cli.komiser.io/2.4.0/osx/komiser" in meantime.

**Comment by mlabouardy** [comment]
@sourabh-kalal thanks for the workaround
@jtbonhomme I've done the fix [here](https://github.com/komiserio/homebrew-komiser/commit/029ae1ee83a3d6a6b01458f504f2d811fd0877ab), also the latest release support now Azure as a provider
