### ISSUE TITLE
Geo Map is not working.

### ISSUE THREAD

**Issue by starsunny** [mlabouardy/komiser#159]
Hi,

Can someone please help, I am unable to see map.

<img width="1138" alt="Screenshot 2021-05-15 at 1 02 37 PM" src="https://user-images.githubusercontent.com/20131173/118352218-d42a1800-b57d-11eb-98fd-5f8c87112b10.png">

<img width="467" alt="Screenshot 2021-05-15 at 1 10 24 PM" src="https://user-images.githubusercontent.com/20131173/118352424-fec8a080-b57e-11eb-878a-a77ceef5ac6d.png">

**Comment by mlabouardy** [comment]
@starsunny we did a fix in the latest release [v2.5.0](https://github.com/mlabouardy/komiser/releases/tag/2.5.0) (it includes the Azure support as well)
