### ISSUE TITLE
EC2 with Instance Profile:: Not getting EC2 running instance and Regions count on ec2 instance 

### ISSUE THREAD

**Issue by deepakkashyap2** [mlabouardy/komiser#186]
Hi Team,

I am using komiser for testing and it is working fine on local machine with ~/.aws/credentials  but on ec2 instance by attaching an instance profile, I am not getting EC2 count and Regions count and S3/Network/security related data.

I have tried this by manually assuming role on local with awscli and it is working fine with the same policy (Which I have attached with the instance profile in above case)
aws sts assume-role --role-arn "arn:aws:iam::12334XXXXXXXX" --role-session-name AWSCLI-Session. 
I have tried checking after setting up aws default region env variable also but no luck
I guess it is having some issue picking up data from matadata. Can you please look into this.

I have observed some notification on the interface like ec2:describeinstance and IAM:getUser are missing (These are there on the file provided by you guys).

**Comment by mlabouardy** [comment]
Thanks @deepakkashyap2 we had some issue with IAM role support, we just did a fix, it should be working with the latest release
