### ISSUE TITLE
Not showing any data in Azure

### ISSUE THREAD

**Issue by chaoscreater** [mlabouardy/komiser#189]
I've followed the guide here:
https://docs.komiser.io/providers/azure/

I've added the environment variables to both User and System in sysdm.cpl and loaded up Komiser. However, I don't see any data.

![image](https://user-images.githubusercontent.com/18227319/159419228-a0487dde-5be0-4740-8d26-9bb0dabd8bfd.png)

The service principal I'm using is definitely correct, as I'm using it for Azure DevOps and it works.

Is there a more specific instruction on how to set this up? I'm tryin to do this on a Windows machine.

UPDATE:

I even tried setting it up in here:
https://cloud.komiser.io/

And it wouldn't list any data for my Azure sub.

**Comment by chaoscreater** [comment]
Is this project dead

**Comment by mlabouardy** [comment]
@chaoscreater do you mind sharing the Komiser logs?

**Comment by mlabouardy** [comment]
@chaoscreater on the on-premise version, you should have logs, no?
can you give me your email address so I can check the hosted version logs as well

**Comment by chaoscreater** [comment]
Sorry, but you really need to provide better documentations or instructions on how to get the logs. 

I ran the onprem version and there are no logs generated that I could see. I could do a Procmon trace to find out if it's storing logs in %appdata% or %localappdata% or somewhere, but I shouldn't have to do that.

The only "logs" that I could see is what's generated in the console in my Powershell:

```
> .\komiser.exe start --port 3000
2022/03/30 22:24:49 Using in-memory cache
::1 - - [30/Mar/2022:22:24:54 +1300] "GET / HTTP/1.1" 200 22149
::1 - - [30/Mar/2022:22:24:55 +1300] "GET /runtime.70b7f973647a1732.js HTTP/1.1" 200 1166
::1 - - [30/Mar/2022:22:24:55 +1300] "GET /polyfills.6ae8e3385bc0c143.js HTTP/1.1" 200 68350
::1 - - [30/Mar/2022:22:24:55 +1300] "GET /main.3006cec8a3ded266.js HTTP/1.1" 200 2172399
::1 - - [30/Mar/2022:22:24:55 +1300] "GET /styles.ecfcf3f49b831a63.css HTTP/1.1" 200 520
::1 - - [30/Mar/2022:22:24:55 +1300] "GET /scripts.d5cb4e7efdff81c8.js HTTP/1.1" 200 681602
::1 - - [30/Mar/2022:22:24:56 +1300] "GET /aws/profiles HTTP/1.1" 200 2
2022/03/30 22:24:56 invalid value specified for AZURE_USE_DEVICEFLOW, disabling
::1 - - [30/Mar/2022:22:24:56 +1300] "GET /gcp/resourcemanager/projects HTTP/1.1" 500 70
2022/03/30 22:24:56 invalid value specified for AZURE_SAMPLES_KEEP_RESOURCES, discarding
2022/03/30 22:24:56 invalid value specified for AZURE_USE_DEVICEFLOW, disabling
2022/03/30 22:24:56 invalid value specified for AZURE_SAMPLES_KEEP_RESOURCES, discarding
::1 - - [30/Mar/2022:22:24:56 +1300] "GET /azure/billing/total HTTP/1.1" 500 41
2022/03/30 22:24:56 http: panic serving [::1]:51909: MSI not available
goroutine 26 [running]:
net/http.(*conn).serve.func1(0xc00042a140)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x30821e0, 0xc000322260)
        /usr/local/go/src/runtime/panic.go:975 +0x499
github.com/mlabouardy/komiser/services/azure.getVMClient(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/mlabouardy/komiser/services/azure/vm.go:17 +0x237
github.com/mlabouardy/komiser/services/azure.Azure.DescribeVMs(0x0, 0x0, 0xd, 0x0, 0x0, 0xc000532100, 0xd)
        /go/src/github.com/mlabouardy/komiser/services/azure/vm.go:44 +0x5f
github.com/mlabouardy/komiser/handlers/azure.(*AzureHandler).VMHandler(0xc0002aeea0, 0x1547b6158b8, 0xc000115e60, 0xc000248100)
        /go/src/github.com/mlabouardy/komiser/handlers/azure/vm_handler.go:21 +0x152
net/http.HandlerFunc.ServeHTTP(0xc00040e630, 0x1547b6158b8, 0xc000115e60, 0xc000248100)
        /usr/local/go/src/net/http/server.go:2042 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00038b880, 0x1547b6158b8, 0xc000115e60, 0xc000698000)
        /go/pkg/mod/github.com/gorilla/mux@v1.6.2-0.20180501031136-ded0c29b24f9/mux.go:162 +0x10f
github.com/rs/cors.(*Cors).Handler.func1(0x1547b6158b8, 0xc000115e60, 0xc000698000)
        /go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c8
net/http.HandlerFunc.ServeHTTP(0xc0004ac8c0, 0x1547b6158b8, 0xc000115e60, 0xc000698000)
        /usr/local/go/src/net/http/server.go:2042 +0x4b
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x3a70480, 0xc000006018, 0x3a726e0, 0xc0004ac8c0, 0x3a95900, 0xc00023c000, 0xc000698000)
        /go/pkg/mod/github.com/gorilla/handlers@v1.3.1-0.20180416203909-2b8556b16671/handlers.go:69 +0x244
net/http.serverHandler.ServeHTTP(0xc000548000, 0x3a95900, 0xc00023c000, 0xc000698000)
        /usr/local/go/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00042a140, 0x3aa65c0, 0xc00003e240)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36d
::1 - - [30/Mar/2022:22:24:56 +1300] "GET /favicon.ico HTTP/1.1" 200 1150
::1 - - [30/Mar/2022:22:25:02 +1300] "GET /favicon.ico HTTP/1.1" 304 0

```


I don't think that's the logs you're looking for and I'd like to look at what's actually in the logs before I hand them to you. I don't want my Azure tenant ID and client secret out in the public.

BTW, here's what I've configured in environment path as per your Azure instructions (which is super minimal):

![image](https://user-images.githubusercontent.com/18227319/160799453-e22193f2-a648-4d6f-a5df-8221f5f13ffd.png)

**Comment by mlabouardy** [comment]
@chaoscreater Komiser streams logs in stdout so the "Powershell" logs is what I needed, thanks ;) 
I'll check that and get back to you in a few

**Comment by mlabouardy** [comment]
It seems like the Azure SDK can't find the env variables so it fall back to Azure Managed Service Identity (hence the MSI not available error) for authorization (works on Azure VMs only) - see https://github.com/Azure/azure-sdk-for-go/issues/16898
I'll try to reproduce the issue on a Windows locally

**Comment by enekux** [comment]
+1 Azure provider is also not working for us using docker

**Comment by mlabouardy** [comment]
We've recently fixed [Azure](https://github.com/mlabouardy/komiser/commit/efba90c46840a61a3029c9acc256e1c23c286775) and updated the [doc](https://help.oraculi.io/en/articles/6316629-connect-azure-account-on-oraculi) as well. I'll close the issue for now but let me know if the problem still persists :)

**Comment by chaoscreater** [comment]
I've just tested again and it still doesn't work. I looked at the docs and created an App Registration and put in the client ID of the app and the Secret value. Put in my tenant ID and sub ID, all correct.

The metrics/stats aren't updating at all.

**Comment by chaoscreater** [comment]
@mlabouardy still not working
