### ISSUE TITLE
New Provider compatible AWS

### ISSUE THREAD

**Issue by Dawns92** [mlabouardy/komiser#198]
Hi, 

I work for Outscale, French Cloud Provider, we use aws cli compatibility to build own infra 
It's possible to change endpoint AWS, or add Outscale like Cloud provider ?
Thanks

**Comment by mlabouardy** [comment]
Hey @Dawns92 
Yes, you can add Outscale as a provider. You can join us on [Discord](https://discord.oraculi.io/) and I can share some guidelines on how to contribute to the project :)
