### ISSUE TITLE
Getting "exec /usr/bin/komiser: exec format error" after upgrading to latest image (docker)

### ISSUE THREAD

**Issue by enekux** [mlabouardy/komiser#200]
**Describe the bug**
We are getting "exec /usr/bin/komiser: exec format error" after upgrading to latest image (docker)

**Comment by mlabouardy** [comment]
@enekux we did a fix [here](https://github.com/mlabouardy/komiser/commit/f1106b86a9c2b049e638a9a4bdd1ec31a04db78c) thanks for reporting it
