### ISSUE TITLE
Windows .exe is not the correct version

### ISSUE THREAD

**Issue by chaoscreater** [mlabouardy/komiser#204]
This downloads version 2.6 for Windows, not 2.7.
`wget https://cli.komiser.io/2.7.0/windows/komiser -OutFile komiser.exe`

Can you please add the .exe binary to Releases? I can't seem to find the latest Windows version.

**Comment by mlabouardy** [comment]
@chaoscreater thanks for reporting the issue
actually you're running v2.7 version, I just forgot to upgrade the version on the CLI itself (https://github.com/mlabouardy/komiser/commit/721271b9a7a897eb8d4f34849ce8a7ea942e95f4)
