### ISSUE TITLE
Statistics for Elastic Load Balancers do not load

### ISSUE THREAD

**Issue by rkujawa** [mlabouardy/komiser#209]
**Describe the bug**
I would like to see statistics related to Elastic Load Balancers in Komiser web UI. I don't see them and frontend is acting as if it is loading these stats.

**To Reproduce**
- Open Komiser web UI Network tab. 
- Observer the frontend trying to load ELB stats, which never happens.

**Expected behavior**
I expect to see the number of ELBs and the load balancer types graph.

**Screenshots**
Komiser Pod throws the following error:
```
2022/07/27 15:10:08 http: panic serving 127.0.0.1:53816: runtime error: invalid memory address or nil pointer dereference
goroutine 41449 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x163cb80, 0x261dab0})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/mlabouardy/komiser/services/aws.AWS.getElasticLoadBalancersV2({}, {{0xc002430690, 0xc}, {0x1c2dac0, 0xc002013b40}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/go/src/github.com/mlabouardy/komiser/services/aws/elb.go:121 +0x1fc
github.com/mlabouardy/komiser/services/aws.AWS.DescribeElasticLoadBalancer({}, {{0xc000044013, 0xc}, {0x1c2dac0, 0xc002013b40}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
	/go/src/github.com/mlabouardy/komiser/services/aws/elb.go:27 +0x1c8
github.com/mlabouardy/komiser/handlers/aws.(*AWSHandler).ElasticLoadBalancerHandler(0xc0004e4cd8, {0x1c3fc08, 0xc001c3b200}, 0xc000378780?)
	/go/src/github.com/mlabouardy/komiser/handlers/aws/elb_handler.go:28 +0x3f8
net/http.HandlerFunc.ServeHTTP(0xc000f43200?, {0x1c3fc08?, 0xc001c3b200?}, 0x5f0000c000679cd0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002063c0, {0x1c3fc08, 0xc001c3b200}, 0xc002c26500)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x1c3fc08, 0xc001c3b200}, 0xc002c26500)
	/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4
net/http.HandlerFunc.ServeHTTP(0x1c3f008?, {0x1c3fc08?, 0xc001c3b200?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/gorilla/handlers.loggingHandler.ServeHTTP({{0x1c32d40, 0xc000010018}, {0x1c349a0, 0xc00003d060}, 0x192c398}, {0x1c3f008, 0xc001018ee0}, 0xc002c26500)
	/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/logging.go:47 +0xef
net/http.serverHandler.ServeHTTP({0xc00278d350?}, {0x1c3f008, 0xc001018ee0}, 0xc002c26500)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0028bfb80, {0x1c3ffc0, 0xc000180e10})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Browser: Safari
 - Version: 15.6

**Comment by jakepage91** [comment]
Thanks a million for opening the bug, we will get to it as quickly as possible @rkujawa. In the meantime, I would like to invite you to our [Discord server](https://discord.oraculi.io/) where you'll be able to find quicker support and it's also a great place to tell us what features you would like to see on the platform that would make your life easier, see you there hopefully!

**Comment by mlabouardy** [comment]
@rkujawa thanks for reporting the issue, we did a fix https://github.com/mlabouardy/komiser/commit/39e3b8b80805799c756d50e7ad46d42f18fa9e48

**Comment by rkujawa** [comment]
In latest image `mlabouardy/komiser:06861a8359bec0910ec12efb45e8505b0a008004` I can see both amount of load balancers and the network vs application load balancer graph. 

The `Today Incoming Requests` is still 0, but I guess this is for CloudFront, not ELB?

**Comment by rkujawa** [comment]
@jakepage91 Thanks for the invitation, but I am not a Discord fan. I can drop some ideas on your GitHub Discussions page, and also as feature requests here in Issues.

**Comment by mlabouardy** [comment]
> In latest image `mlabouardy/komiser:06861a8359bec0910ec12efb45e8505b0a008004` I can see both amount of load balancers and the network vs application load balancer graph.
> 
> The `Today Incoming Requests` is still 0, but I guess this is for CloudFront, not ELB?

exactly its for CloudFront

**Comment by jakepage91** [comment]
@rkujawa that works perfectly well too, cheers!
