### ISSUE TITLE
Redis clusters counter shows amount of nodes, not amount of clusters

### ISSUE THREAD

**Issue by rkujawa** [mlabouardy/komiser#211]
**Describe the bug**
The counter of Redis clusters seems to work incorrectly. I have 2 Redis clusters, both have 3 nodes. So I suspect, the counter is in fact showing the total amount of nodes, not amount of clusters.

**To Reproduce**
- Go into Storage tab of Komiser web UI
- Scroll down to "Redis clusters"
- See wrong amount

**Expected behavior**
I expect to see the correct amount of clusters. Though, knowing the amount of nodes could also be useful, so it could be a separate counter.

**Screenshots**
It just shows:
```
Redis Clusters
6 
```

**Desktop (please complete the following information):**
 - OS: MacOS 12.5
 - Browser: Safari
 - Version: 15.6

**Additional context**
I think this is just an error with parsing of API response. The API for Redis clusters is kinda weird and counterintuitive:
```
$ aws elasticache describe-cache-clusters | jq '.CacheClusters[].CacheClusterId'
"redis-prod-001"
"redis-prod-002"
"redis-prod-003"
"redis-test-001"
"redis-test-002"
"redis-test-003"
$ aws elasticache describe-cache-clusters | jq '.CacheClusters[].ReplicationGroupId'
"redis-prod"
"redis-prod"
"redis-prod"
"redis-test"
"redis-test"
"redis-test"
```
These are just two clusters.

**Comment by mlabouardy** [comment]
@rkujawa fixed as well here https://github.com/mlabouardy/komiser/commit/04c82cb1105ea2ef302ba7a2c3788ff733942ae3

**Comment by rkujawa** [comment]
Works correctly in latest image `mlabouardy/komiser:06861a8359bec0910ec12efb45e8505b0a008004`.
