### ISSUE TITLE
Snapshots count and size include public snapshots

### ISSUE THREAD

**Issue by alexbilbie** [mlabouardy/komiser#28]
I've just discovered this project and it's really cool 👍 

Something I noticed is the snapshots count and size include public snapshots - ideally these numbers should be limited to private snapshots.

<img width="468" alt="screen shot 2018-03-20 at 16 30 18" src="https://user-images.githubusercontent.com/77991/37668270-01a28d98-2c5c-11e8-83ad-80b057ca49fc.png">

**Comment by mlabouardy** [comment]
Thanks for reporting. It will be fixed soon 😊

**Comment by mlabouardy** [comment]
@alexbilbie has been fixed :) https://github.com/mlabouardy/komiser/commit/ac96718ea8b8f1fbbbd572d876a335d9763b6025
