### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tskinn** [mlabouardy/komiser#31]
Awesome project!

I'm just wondering what your vision is for this project. I saw your todo list at the bottom of the readme but was curious if you have more in mind than that.

I'd love to contribute but just wanted to check before I end up in the bushes with a bunch of code going a direction you weren't intending to explore.

**Comment by mlabouardy** [comment]
Sure 😊 first i want to collect all information about critical AWS services. Next, based on the information we collected , give the user recommendation on hiw to optimize its infrasratructure by analyzing the data and

**Comment by mlabouardy** [comment]
I appreciate your interest in the project. Well, first I want to collect information about all critical AWS services. Next, based on the data we collected, will do some analytics to give the user some recommendations about things he can do to optimize his infrastructure and reduce its cost (for example: remove unused volumes or snapshots, release unused Elastic IPs ...)

**Comment by mlabouardy** [comment]
PS: we can even go further and implement some call-to-action directly in the dashboard for people unfamiliar with AWS Management Console, to make the process straighforward

**Comment by mlabouardy** [comment]
I created a slack team for further discussion https://komiser.slack.com
