### ISSUE TITLE
us-east-1 in the incorrect location on map.

### ISSUE THREAD

**Issue by davidjeddy** [mlabouardy/komiser#32]
Love the project, really helpful and handy tool. Only small issue I could see out-of-the-box for the https://github.com/mlabouardy/komiser/commit/7e85479c30b3e978528c50fc79b1e577cf393b9e commit point is that the US-EAST-1 dot on the map is on the incorrect side of the contentment.

![komiser-us-east-1-wrong-location](https://user-images.githubusercontent.com/6232455/37752724-d0016e02-2d6f-11e8-9fb1-f8ca152497db.jpg)

**Comment by mlabouardy** [comment]
@davidjeddy thanks for reporting, just fixed https://github.com/mlabouardy/komiser/commit/5e4941600d55e3deee7bd3b8de77b7fffcaeb8a1 :)
