### ISSUE TITLE
Ability To Specify An AWS Profile 

### ISSUE THREAD

**Issue by toneill818** [mlabouardy/komiser#34]
Currently if you run komiser and use the Shared Credentials File (~/.aws/credentials) it only uses the default credentials. If the shared credentials contains multiple accounts there is no easy way to switch between.

**Comment by mlabouardy** [comment]
Good feature, I added to the roadmap 👍

**Comment by mlabouardy** [comment]
@toneill818 by the way you always override the default profile by setting AWS_PROFILE environment variable (https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html)

**Comment by toneill818** [comment]
@mlabouardy Yeah, that is possible. I was thinking an optional profile flag to program would be best. For example I have multiple accounts I could run many instances of komiser with different ports for each. 

`komiser start -p 3000 --profile development`
`komiser start -p 3001 --profile stage`
`komiser start -p 3002 --profile production`

**Comment by mlabouardy** [comment]
@toneill818 got it, I will implemented soon, meanwhile you can always launch multiple instances this way:

```
AWS_PROFILE=development komiser start -p 3000 
AWS_PROFILE=staging komiser start -p 3001
AWS_PROFILE=production komiser start -p 3002 
```
