### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by trondhindenes** [mlabouardy/komiser#38]
I got here from the post on HN. After reading the intro around cost optimization I got the impression Komiser could be use for finding unused resources in aws, but as I read more it doesn't do that - its a "condensed" view of all aws resources, is that right? I still don't have a full grasp on the actual use case - it would be awesome if komiser for instance would report on security groups that arent used anywhere, disconnected EBS volumes, snapshots that point to non-existing instance, buckets that havent been read from / written to in the last x amount of days - stuff like that.

**Comment by mlabouardy** [comment]
it's part of the roadmap.at the moment, you have a global overview of your aws resources, in upcoming release you can do a drill down and have recommendations on unused resources you can remove or shutdown to reduce your costs

**Comment by trondhindenes** [comment]
awesome, looking forward to it!
