### ISSUE TITLE
Total Bill

### ISSUE THREAD

**Issue by rajanbaski** [mlabouardy/komiser#41]
Hi,
I get ce:GetCostAndUsage is missing error in the notification. I did add the policy to allow IAM users to use the AWS Cost Explorer API following Example 12 from: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-permissions-ref.html#example-policy-ce-api

but still face the issue

**Comment by mlabouardy** [comment]
it's bug in the AWS SDK not the CLI itself, it will be fixed in the upcoming release
