### ISSUE TITLE
my site display RDS Instances number is not correct

### ISSUE THREAD

**Issue by caoye126** [mlabouardy/komiser#48]
my site display RDS Instances number is not correct:
![default](https://user-images.githubusercontent.com/26160361/39616730-7a230a74-4faf-11e8-973a-006edd09652e.png)
actual my RDS instances number is 2 and my credentials is correct.
plz help me, ths.

**Comment by mlabouardy** [comment]
@caoye126 do you have the `rds:DescribeDBInstances` permission ? can you tell me also what's shown in the notification bar 
<img width="212" alt="screen shot 2018-05-08 at 12 44 27" src="https://user-images.githubusercontent.com/10320205/39753011-9cb04a78-52bd-11e8-8028-b867502e153d.png">

**Comment by mlabouardy** [comment]
@caoye126 fixed by https://github.com/mlabouardy/komiser/pull/54
