### ISSUE TITLE
Few Services Returning "HTTP 500"

### ISSUE THREAD

**Issue by Aravee** [mlabouardy/komiser#51]
Hi,

My site is returning 500 for few services. The log is below.

157.49.247.213 - - [28/Oct/2018:05:02:07 +0000] "GET / HTTP/1.1" 200 1745
157.49.247.213 - - [28/Oct/2018:05:02:07 +0000] "GET /styles.05d4aeeb77605b05dbf9.bundle.css HTTP/1.1" 200 12557
157.49.247.213 - - [28/Oct/2018:05:02:07 +0000] "GET /inline.3ccb99ed5f99f84b8ce6.bundle.js HTTP/1.1" 200 1445
157.49.191.99 - - [28/Oct/2018:05:02:08 +0000] "GET /polyfills.abdf53ca655716e505e0.bundle.js HTTP/1.1" 200 59417
157.49.191.99 - - [28/Oct/2018:05:02:08 +0000] "GET /main.ec2b6339a7c503308fbf.bundle.js HTTP/1.1" 200 1202122
157.49.191.99 - - [28/Oct/2018:05:02:10 +0000] "GET /acl HTTP/1.1" 500 46
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /nat HTTP/1.1" 500 46
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /security_group HTTP/1.1" 500 46
157.49.191.99 - - [28/Oct/2018:05:02:10 +0000] "GET /vpc HTTP/1.1" 500 46
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /eip HTTP/1.1" 500 46
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /internet_gateway HTTP/1.1" 500 46
157.49.191.99 - - [28/Oct/2018:05:02:10 +0000] "GET /key_pair HTTP/1.1" 500 46
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /route_table HTTP/1.1" 500 46
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /autoscaling_group HTTP/1.1" 500 60
157.49.191.99 - - [28/Oct/2018:05:02:10 +0000] "GET /dynamodb HTTP/1.1" 500 68
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /ebs HTTP/1.1" 500 42
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /snapshot HTTP/1.1" 500 44
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /elb HTTP/1.1" 500 65
157.49.247.213 - - [28/Oct/2018:05:02:10 +0000] "GET /lambda HTTP/1.1" 500 43
157.49.191.99 - - [28/Oct/2018:05:02:10 +0000] "GET /sqs HTTP/1.1" 500 37
157.49.247.213 - - [28/Oct/2018:05:02:11 +0000] "GET /sns HTTP/1.1" 500 37
157.49.247.213 - - [28/Oct/2018:05:02:11 +0000] "GET /cloudwatch HTTP/1.1" 500 48
157.49.191.99 - - [28/Oct/2018:05:02:11 +0000] "GET /iam/group HTTP/1.1" 200 1
157.49.247.213 - - [28/Oct/2018:05:02:11 +0000] "GET /hosted_zone HTTP/1.1" 200 1
157.49.247.213 - - [28/Oct/2018:05:02:11 +0000] "GET /iam/policy HTTP/1.1" 200 3
157.49.247.213 - - [28/Oct/2018:05:02:11 +0000] "GET /iam/role HTTP/1.1" 200 2
157.49.191.99 - - [28/Oct/2018:05:02:10 +0000] "GET /cost HTTP/1.1" 200 639
157.49.247.213 - - [28/Oct/2018:05:02:11 +0000] "GET /iam/user HTTP/1.1" 200 1
157.49.247.213 - - [28/Oct/2018:05:02:11 +0000] "GET /s3 HTTP/1.1" 500 42
157.49.191.99 - - [28/Oct/2018:05:02:11 +0000] "GET /cloudfront HTTP/1.1" 200 1
157.49.247.213 - - [28/Oct/2018:05:02:11 +0000] "GET /ec2 HTTP/1.1" 500 44

The below permission is for ec2 and i feel permissions are fine. 

![image](https://user-images.githubusercontent.com/11864887/47612305-1d88e980-da9e-11e8-9342-b4ad852a63a6.png)

Site Notification:

![image](https://user-images.githubusercontent.com/11864887/47612320-5a54e080-da9e-11e8-8ce8-89eb6b2a5e2d.png)

**Comment by mlabouardy** [comment]
@Aravee  sorry for late response , this issue was fixed in the new release
