### ISSUE TITLE
Multiple regions in my aws account.

### ISSUE THREAD

**Issue by shivamhot91** [mlabouardy/komiser#53]
Hi,

We have multiple Ec2 instances and S3 buckets in multiple regions in one account. Can I monitor all regions resources from this komiser tool?
Please also tell us, Can we monitor multiple accounts from a single komiser tool?

**Comment by mlabouardy** [comment]
@shivamhot91 please check the new release

**Comment by gabriel-dima-gr** [comment]
Hi, I am usning the latest release. Is there anywhere documented how to go across multiple AWS accounts?
