### ISSUE TITLE
Number of api request and additional costing over head

### ISSUE THREAD

**Issue by Praneetmane** [mlabouardy/komiser#56]
Hello Mohamed,
Thanks for this wonderful tool. Can you please help me in understanding for the number of request being generated when we hit refresh on dashboard. I am looking for a estimate from additional costing perspective (AWS Reference https://aws.amazon.com/api-gateway/pricing/ ). Any help in this regards will be highly appreciated.

Thanks & Regards
Praneet Mane
![apicost](https://user-images.githubusercontent.com/34704107/53171158-fc797500-3607-11e9-8cec-61ee172c0daa.png)

**Comment by mlabouardy** [comment]
I'm not sure I fully understand, API Gateway requests are now supported in the new release :)
