### ISSUE TITLE
No data for storage

### ISSUE THREAD

**Issue by 80kk** [mlabouardy/komiser#60]
In the Storage tab, there is no data for:
S3 Size, S3 Objects, Empty buckets, S3 Bucket size, S3 Bucket objects. Also clicking on the issue under the Bell icon takes me back to the dashboard without displaying further info.
Alarms tab is shining in red, but it is not providing any further information.

**Comment by mlabouardy** [comment]
Hello @80kk 

you need to add the following policies:

```
s3:ListAllMyBuckets
cloudwatch:GetMetricStatistics
s3:GetBucketLocation
```
