### ISSUE TITLE
Active instances dot color blend in with the map on hover

### ISSUE THREAD

**Issue by lesaff** [mlabouardy/komiser#66]
Thanks for writing this app. It's really useful!

On the Dashboard, the map hover color should probably be set to a different color to avoid blending in with the active region.

![komiser-region-map](https://user-images.githubusercontent.com/1151181/57373266-5a7d1980-716e-11e9-89d2-d7a4ff6aa022.gif)

**Comment by mlabouardy** [comment]
@lesaff fixed, I also added the support of GCP
