### ISSUE TITLE
GCP Support?

### ISSUE THREAD

**Issue by steinbrueckri** [mlabouardy/komiser#70]
Hi Guys,
I have found the following in the README ...

> Get a deep understanding of how you spend on the AWS, **GCP** and Azure.

But I can't see anything regarding GCP, will this feature come later or missed i something?
Br Richard

**Comment by mlabouardy** [comment]
@steinbrueckri it will be released this weekend

**Comment by mlabouardy** [comment]
@steinbrueckri just released the support of GCP
