### ISSUE TITLE
[ turns into Æ

### ISSUE THREAD

**Issue by bboonen** [mlabouardy/komiser#74]
Hi @mlabouardy while passing the credentials file into the docker container with this command:

docker run -d -p 3000:3000 -v $HOME/.aws/credentials:/root/.aws/credentials --name komiser mlabouardy/komiser:2.1.0

the [default] sections of the credentials file turns into ÆdefaultÆ

**Comment by mlabouardy** [comment]
hmm weird, let me check that

**Comment by bboonen** [comment]
Changing to the right timezone and keyboard layout same as my local mac does the trick.

**Comment by mlabouardy** [comment]
thanks for the update @bboonen
