### ISSUE TITLE
Permissions issues (Support cases, S3 Objects, ECS clusters, etc) - Docker on ECS

### ISSUE THREAD

**Issue by dfeldstarsky** [mlabouardy/komiser#87]
Hiya - love the app and dashboard. Running into some issues similar to #85 and other permissions issues.

I can't see ECS clusters, S3 object size, number of support cases, etc. I have attached your komiser policy to the ECS workspace role and most of the permissions are working! 

![image](https://user-images.githubusercontent.com/30241048/58205184-d1e49a00-7c92-11e9-865e-b1c72627ac5e.png)

Permission issues shown. 0 bucket size for s3 shown.

I am deploying on ECS Fargate, with a task definition attached.

Logs showing 500 errors:
![image](https://user-images.githubusercontent.com/30241048/58205266-02c4cf00-7c93-11e9-97a7-3ed7008739c4.png)

Task def json:
```
[
    {
        "name": "komiser-task-def",
        "image": "<acc_name>.dkr.ecr.us-west-2.amazonaws.com/komiser:latest",
        "cpu": 512,
        "memory": 1024,
        "essential": true,
        "portMappings": [
            {
                "containerPort": 80,
                "hostPort": 80,
                "protocol": "tcp"
            },
            {
                "containerPort": 3000,
                "hostPort": 3000,
                "protocol": "tcp"
            }
        ],
        "logConfiguration": {
            "logDriver": "awslogs",
            "options": {
                "awslogs-group": "/aws/ecs/komiser",
                "awslogs-region": "us-west-2",
                "awslogs-stream-prefix": "komiser"
            }
        },
        "healthCheck": {
            "command": ["CMD-SHELL", "curl -f http://localhost || exit 1"],
            "interval": 30,
            "retries": 2,
            "timeout": 5
        },

        "environment": [
                    {
                        "name":"PORT",
                        "value":"80"
                    },
                    {
                        "name":"AWS_DEFAULT_REGION",
                        "value":"us-west-2"
                    }

                ],

        "mountPoints": [],
        "volumesFrom": []
    }
]

```

**Comment by dfeldstarsky** [comment]
Seem to have the right environment variables:
![image](https://user-images.githubusercontent.com/30241048/58205466-74048200-7c93-11e9-895c-3a502def1307.png)

**Comment by mlabouardy** [comment]
Hello @dfeldstarsky , thanks for reporting this out.

You need to add ""s3:GetBucketLocation"" permission to the IAM role :)

**Comment by mlabouardy** [comment]
I have updated the IAM policy with the missing permissions: https://github.com/mlabouardy/komiser/blob/master/policy.json

Let me know, if that fix your issues

**Comment by dfeldstarsky** [comment]
@mlabouardy thanks so much for the quick reply + suggested fix. I applied the permissions change from your new policy and indeed I now get all the S3 metrics :).

Now the only permissions problems I see are AWS Support cases and correct ECS cluster counts. Cluster counts is still at 0 despite us having ~5. And we have 2 open AWS support cases.

Current 500 errors:
![image](https://user-images.githubusercontent.com/30241048/58268842-14fa4800-7d3b-11e9-8aaf-a15ed822cc71.png)

**Comment by mlabouardy** [comment]
@dfeldstarsky you can fix AWS support cases issue by using "support:*" (I have updated the IAM policy)

**Comment by mlabouardy** [comment]
@dfeldstarsky I was able to reproduce the issue regarding ECS clusters, I will fix that by the end of today, meanwhile, I will close this ticket, and I let you raise an issue regarding ECS if you dont mind :)

**Comment by dfeldstarsky** [comment]
Done, opened a new issue 👍
