### ISSUE TITLE
AWS Policies missing + Can view all notifications

### ISSUE THREAD

**Issue by dimisjim** [mlabouardy/komiser#89]
By running latest release with docker (and by setting the region var).

Getting these: 
![image](https://user-images.githubusercontent.com/6890249/58374412-0a5bd080-7f3e-11e9-96df-4be9bcf464d8.png)

Furthermore, the "view all notifications" button doesn't work (nothing happens after press).

**EDIT:** After a refresh of the dashboard, I only get the cases policy missing only.
Also, the Alarms count (which btw, how do I view them?) changes after a refresh.

**Comment by mlabouardy** [comment]
@dimisjim sorry for late response, I'm working on a fix, will be released this week :)

**Comment by aliaskov** [comment]
Also iam:GetUser is missing for me

**Comment by mlabouardy** [comment]
@aliaskov its in the IAM policy -> https://github.com/mlabouardy/komiser/blob/master/policy.json#L97

**Comment by aliaskov** [comment]
> @aliaskov its in the IAM policy -> https://github.com/mlabouardy/komiser/blob/master/policy.json#L97

I have this policy applied, with iam:GetUser, but web UI complains. 

GET https://komiser.x.eks.XXXXXX-staging.io/aws/iam/account 500

**Comment by mlabouardy** [comment]
it's normal, if you're using an IAM role instead of credentials (or environment variables), the AWS SDK wont be able to fetch the user, because there's no user behind an IAM role

**Comment by gamefundas** [comment]
I also wonder if Komiser needs proxy configurations in case of firewalls in an enterprise network. As in my case most things were failing and the entire loads empty.

**Comment by mlabouardy** [comment]
@gamefundas did you set AWS_DEFAULT_REGION environment variable ?

**Comment by gamefundas** [comment]
@mlabouardy I managed to get it running by passing environment proxy variables.
-e "HTTPS_PROXY=http://myproxy:3128" -e "NO_PROXY=localhost,127.0.0.1"

**Comment by mlabouardy** [comment]
@dimisjim you can now view notifications https://github.com/mlabouardy/komiser/releases/tag/2.2.0

**Comment by dimisjim** [comment]
Thanks @mlabouardy notifications in docker now work.

But I am still getting missing permissions:
![image](https://user-images.githubusercontent.com/6890249/58947096-ea26df80-878f-11e9-96e8-8a0dc1ac90c6.png)
