### ISSUE TITLE
AWS IAM role does not work

### ISSUE THREAD

**Issue by aliaskov** [mlabouardy/komiser#90]
komiser is in eks. 
Policy and role created. Trusted entities - correct ( EKS cluster). Same as for other services.  

`apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: komiser
  name: komiser
  namespace: monitoring-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komiser
  strategy: {}
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::XXXXXXXXXX:role/komiser-aws-overview
      creationTimestamp: null
      labels:
        app: komiser
    spec:
      containers:
      - image: mlabouardy/komiser:latest
        name: komiser
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
`
+ service + ingress. Works fine. 
Pod has a role assigned : 

`Name:               komiser-6d85967d85-scn9t
Namespace:          monitoring-core
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-120-70-200.eu-west-1.compute.internal/10.120.70.200
Start Time:         Fri, 24 May 2019 15:56:54 +0200
Labels:             app=komiser
                    pod-template-hash=6d85967d85
Annotations:        iam.amazonaws.com/role: arn:aws:iam::XXXXXXXXXX:role/komiser-aws-overview
Status:             Running`

Some data is displayed ( number of users, billing info on a start page) , but lots of important info is missing. Some errors: 

> You have 13 new notification
cloudwatch:DescribeAlarms is missing
219 minutes ago
ec2:DescribeInstances is missing
219 minutes ago
tag:GetResources is missing
19 minutes ago
iam:GetUser is missing
19 minutes ago
support:DescribeCases is missing
219 minutes ago
cloudwatch:GetMetricStatistics is missing
219 minutes ago
ec2:DescribeElasticIPs is missing
19 minutes ago
lambda:ListFunctions is missing
19 minutes ago
ecs:DescribeClusters or ecs:DescribeTasks or ecs:DescribeServices is missing
19 minutes ago
ec2:DescribeScheduledInstances is missing
19 minutes ago
ec2:DescribeSpotFleetRequests is missing
19 minutes ago
ec2:DescribeReservedInstances is missing
19 minutes ago
eks:ListClusters is missing
19 minutes ago

**Comment by mlabouardy** [comment]
@aliaskov you need to set the AWS_DEFAULT_REGION environment variable

**Comment by aliaskov** [comment]
added 
        env:
        - name: AWS_DEFAULT_REGION
          value: "eu-west-1"

With this I've lost billing and Route53 data =) nothing is displayed now

**Comment by mlabouardy** [comment]
@aliaskov let me know if that solve your issue :)

**Comment by aliaskov** [comment]
Works amazing! I can share k8s deployment if you want. Not rocket science, but anyway...

**Comment by mlabouardy** [comment]
@aliaskov awesome, thanks for the update
