### ISSUE TITLE
question: EBS Size in storage tab

### ISSUE THREAD

**Issue by aliaskov** [mlabouardy/komiser#91]
Why it shows such a small number? 
In my case it shows 5 Gb in one account and 1 Gb in other. In fact I have  45 volumes ( 1Gb - to 100 Gb real size)

**Comment by dfeldstarsky** [comment]
Are you seeing any 4xx/5xx errors in your logs? Perhaps a permissions error or region error not showing on the main dashboard correctly. (Note, I am not the maintainer so take my pointers w/ a grain of salt).

**Comment by aliaskov** [comment]
No 4xx/5xx errors in logs. Also I think EBS Size metric is related to EBS Snapshots somehow

**Comment by mlabouardy** [comment]
@aliaskov I have added some fixes in new release https://github.com/mlabouardy/komiser/releases/tag/2.2.0 let me know if it fixes the issue, if not I will reopen the ticket
