### ISSUE TITLE
prompted for credentials when installing via brew

### ISSUE THREAD

**Issue by virtzilla** [mlabouardy/komiser#92]
Should credentials for GitHub be required to install via brew?

virtzilla:~$ brew tap mlabouardy/komiser
==> Tapping mlabouardy/komiser
Cloning into '/usr/local/Homebrew/Library/Taps/mlabouardy/homebrew-komiser'...
Username for 'https://github.com':

**Comment by mlabouardy** [comment]
hmm weird, l will try to reproduce it, I will get back to you in few hours.

**Comment by virtzilla** [comment]
I see it's marked as invalid. Are you not able to reproduce the issue?

I'm still blocked by the issue as reported, and it's consistently reproducible on my side.

**Comment by mlabouardy** [comment]
@virtzilla I wasnt able to reproduce yet, meanwhile, can you use download the CLI instead: 
```
wget https://cli.komiser.io/2.2.0/osx/komiser
```
I will let you know, once the homebrew package is working 👍

**Comment by fortitude-it** [comment]
I am having this issue too. Looks like the repo homebrew is looking for is: `https://github.com/mlabouardy/homebrew-komiser`
rather than what I expect should be just: 
`https://github.com/mlabouardy/komiser`
which is a 404.

Here's the full output:

```➜ brew tap mlabouardy/komiser
==> Tapping mlabouardy/komiser
Cloning into '/usr/local/Homebrew/Library/Taps/mlabouardy/homebrew-komiser'...
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/mlabouardy/homebrew-komiser/'
Error: Failure while executing; `git clone https://github.com/mlabouardy/homebrew-komiser /usr/local/Homebrew/Library/Taps/mlabouardy/homebrew-komiser --depth=1` exited with 128.```

I'm not very familiar with how homebrew works under the covers, so I am grasping at straws here, but perhaps they have changed their functionality?

**Comment by mlabouardy** [comment]
@fortitude-it the tap is located in komiser organization : https://github.com/komiserio/homebrew-komiser
