### ISSUE TITLE
IAM policy - support:CreateCase?

### ISSUE THREAD

**Issue by soukicz** [mlabouardy/komiser#93]
It might be by design but there are permissions like "support:CreateCase" in recommended policy: https://raw.githubusercontent.com/mlabouardy/komiser/master/policy.json
Every other permission is read only but you could probably do some damage with full access to support.

**Comment by mlabouardy** [comment]
support:DescribeCases is not enough to read tickets, its a bug in the AWS SDK itself, so you can either give full support access in order to get number of tickets or just ignore that @soukicz
