### ISSUE TITLE
Docker version run with Redis cache option

### ISSUE THREAD

**Issue by gamefundas** [mlabouardy/komiser#94]
Is there a way to tell the Docker version of Komiser use a Redis instance as cache. Didn't see any run parameters defined in the Docker image.

**Comment by mlabouardy** [comment]
@gamefundas docker image now support redis, I have updated the README on how to run Komiser docker version with Redis

**Comment by gamefundas** [comment]
I see the PORT parameter exposed, but not for Redis. Tried the following by passing as argument and it didn't seem to make any difference.

docker run -d -p 3000:3000 -e AWS_ACCESS_KEY_ID="" -e AWS_SECRET_ACCESS_KEY="" -e AWS_DEFAULT_REGION="" --name komiser mlabouardy/komiser:2.2.0 komiser start --redis myhost:6379

**Comment by mlabouardy** [comment]
@gamefundas redis is not running inside komiser container, you need to deploy it as an external service and link it to the container:

```
docker run -d --name redis redis
docker run -d -p 3000:3000 -e AWS_ACCESS_KEY_ID="" -e AWS_SECRET_ACCESS_KEY="" -e AWS_DEFAULT_REGION="" --link redis:redis --name komiser mlabouardy/komiser:2.2.0 komiser start --redis localhost:6378
```

**Comment by gamefundas** [comment]
I have to run the container with host networking due to some security restrictions accessing amazon api and hence its unable for me to link containers. I was wondering if there is a way to point to a Redis elasticache instance via configuration.

**Comment by gamefundas** [comment]
@mlabouardy the main idea was to point it to a remote/another redis instance running as AWS ElastiCache service. If only there was a way to specify the Redis server as a parameter it will make the docker image quite flexible to operate.
