### ISSUE TITLE
Resources reported as 'missing' season 2

### ISSUE THREAD

**Issue by l13t** [mlabouardy/komiser#98]
I'm getting messages like:
```
2 cloudwatch:DescribeAlarms is missing 4 minutes ago
ec2:DescribeInstances is missing 4 minutes ago
tag:GetResources is missing 4 minutes ago
2 support:DescribeCases is missing 4 minutes ago
```
and for couple more resources.
I'm pretty sure I've correctly configured policy because I could see activity for a user (where it's attached) in `Access Advisor`.
In code I could see that for any error from AWS API komiser web ui answers `<aws_resource> is missing`.
I think it would be better to return actual error for API call.

**Comment by CyrilAll** [comment]
resolved
