### ISSUE TITLE
Install Komiser in OSx

### ISSUE THREAD

**Issue by gonarys** [mlabouardy/komiser#99]
I tried to install Komiser like as indicated in the documentation but i had this error

brew install komiser
==> Installing komiser from komiserio/komiser
==> Downloading https://cli.komiser.io/2.2.0/osx/komiser
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 08f557e824e465ca307e0609c68ee4d7d24d95aa1d986a132dc17f0019f81757
  Actual: c9a2efb2dc0ef9ce10e2e80ae6ea5bc364ad73b70d3f6f46bbc1c7c4a16cfd27
 Archive: /Users/safouenbenhadj/Library/Caches/Homebrew/downloads/064bfd75fd69e4fd2603f585a74778701c4ce1df97e9ff7be332f1fb470d43b6--komiser
To retry an incomplete download, remove the file above.

**Comment by mlabouardy** [comment]
@gonarys sorry I forgot to update the sha256 on homebrew tap, it should work now

**Comment by francbartoli** [comment]
Same for me with current version `2.4.0`:

```
==> Installing komiser from komiserio/komiser
==> Downloading https://cli.komiser.io/2.4.0/osx/komiser
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 4e4951a12658de0c8bf15806765ae2c6b5b734e45efbef54d2504d1dd1709b71
  Actual: 8958fdec8ae105ecef94fd7d253407f7ecfbdf678dd35ef8c037fd43c623fb86
 Archive: /Users/geobart/Library/Caches/Homebrew/downloads/f32e48996ec2f93bc8274403fba68d229a189861ba05256289577a936b08f353--komiser
To retry an incomplete download, remove the file above.
```

**Comment by johnoshea** [comment]
@mlabouardy FYI, I'm seeing the same thing as @francbartoli - let me know if you want me to raise a new issue for this - thanks

**Comment by rafaljanicki** [comment]
@mlabouardy same here, should you reopen or can I open a new ticket?
